version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "tcl-certificado"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-tczx7jijciaf"
s3_prefix = "tcl-certificado"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
