AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  tcl-certificado

   SAM Template for tcl-certificado
Globals:
  Function:
    Timeout: 3

Parameters:
  CertBucketVar:
    Type: String
    Description: Bucket Certificado
    Default: cert-lncap-tcl
  CertResourcesBucketVar:
    Type: String
    Description: Bucket Certificado Resources
    Default: cert-lncap-resources


Resources:
  CertificadoFunction:
    Type: AWS::Serverless::Function 
    Properties:
      Environment:
          Variables:
            RESOURCE_BUCKET: !Ref CertResourcesBucketVar
            CERT_BUCKET: !Ref CertBucketVar

      CodeUri: certificado/
      Handler: index.handler
      Runtime: nodejs16.x
      Architectures:
        - x86_64

      Layers:
        - !Ref PdfKitLayer
                
      Policies:
        - Statement:
          - Effect: Allow
            Action:
              - s3:*
              - s3-object-lambda:*
            Resource: '*'

      Events:
        Certificado:
          Type: Api 
          Properties:
            Path: /certificado
            Method: get

  PdfKitLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: pdfkit-layer
      Description: Layer pdfkit that will be shared across multiple functions
      LicenseInfo: 'Available under the MIT license.'
      ContentUri: ./pdfkit-layer
      CompatibleRuntimes:
        - nodejs16.x
Outputs:

  CertificadoApi:
    Description: "API Gateway endpoint URL for Prod stage for Certificadofunction"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/certificado/"
  CertificadoFunction:
    Description: "CertificadoLambda Function ARN"
    Value: !GetAtt CertificadoFunction.Arn
  CertificadoFunctionIamRole:
    Description: "IAM Role created for Certificadofunction yo cambien desde Vcode"
    Value: !GetAtt CertificadoFunctionRole.Arn
