AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  tcl-certificado

   SAM Template for tcl-certificado

Globals:
  Function:
    Timeout: 3

Resources:
  CertificadoFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: certificado/
      Handler: app.lambdaHandler
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      Events:
        Certificado:
          Type: Api 
          Properties:
            Path: /certificado
            Method: get

Outputs:

  CertificadoApi:
    Description: "API Gateway endpoint URL for Prod stage for Certificadofunction"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/certificado/"
  CertificadoFunction:
    Description: "CertificadoLambda Function ARN"
    Value: !GetAtt CertificadoFunction.Arn
  CertificadoFunctionIamRole:
    Description: "IAM Role created for Certificadofunction yo cambien desde Vcode"
    Value: !GetAtt CertificadoFunctionRole.Arn
